server:
  port: 8081

spring.h2.console:
  enabled: true
  path: /h2

spring.datasource:
  url: jdbc:h2:mem:userdb;DB_CLOSE_DELAY=-1
  username: sa
  password:
  schema: classpath:database/schema.sql

spring.jpa.hibernate.ddl-auto: none