CREATE TABLE USERDATA (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    USERNAME VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PHONE BIGINT NOT NULL,
    REGISTERED BOOLEAN,
    PRIMARY KEY (ID)
);